In [ ]:
import numpy as np


In [ ]:
#list of numpy array
#1 dimension array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [ ]:
#2 dimension array
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#zero function
arr3 = np.zeros([2, 3])
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#all matics are 0
arr4 = np.ones([3, 4])
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#top to left diagonal
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#arrange
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#linespace
arr7 = np.linspace(10,20,30)
arr7

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [ ]:
arr8 = arr7.copy()
arr8

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

# lect 4
#shap
#nDim
#size
#itemsize
#Dtype()
#astype


In [ ]:
#shape
arr1.shape             #oper 1 dimension array

(5,)

In [ ]:
arr2.shape           #oper 2 dimention array

(2, 3)

In [ ]:
#3 dimention array
arr9 = np.array([[1,2],[3,4],[5,6],[7,8]])
arr9

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**number of dimention**

In [ ]:
arr9.ndim

2

In [ ]:
arr1.ndim

1

In [ ]:
arr2.ndim

2

In [ ]:
arr3.ndim

2

**size**

In [ ]:
arr1.size

5

In [ ]:
arr2.size

6

In [ ]:
arr3.size

6

**D type**


# type batay ga

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr9.dtype

dtype('int64')

**astype**

It creates a new array with the specified type, without changing the original array.
Sometimes you want to change the data type, for example:

Convert integers to floats

Convert floats to integers

Convert numbers to strings

Or change to any other NumPy-supported data type

In [ ]:
arr1.astype

<function ndarray.astype>

In [ ]:
arr9.astype


<function ndarray.astype>

lecture  5

numpy array vs python list

In [ ]:
arr11 = np.arange(100)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#numpy kitna fast hai
x = range(1000)
y = range(1000,2000)
start-time = time.time()
c